### ISSUE TITLE
GeoRDD package installing problem

### ISSUE THREAD

**Issue by Elennahan** [maximerischard/GeoRDD.jl#1]
![2019-02-24_165335](https://user-images.githubusercontent.com/44094996/53297152-ddbbee00-3854-11e9-9e9b-c1036f291e84.png)
I encountered the warning information as showed in the picture. As a new leaner of julia language form China, I will be very appreciated if you can give some ideas to solve this problem.

**Comment by Elennahan** [comment]
Additionally, I use juliapro software to run the code, Pkg.clone("https://github.com/Elennahan/GeoRDD.jl.git"), to install this packge.

**Comment by maximerischard** [comment]
It looks like you're having trouble installing the dependencies.
The dependency chain is: GeoRDD -> GaussianProcesses -> PDMats -> Arpack
Could you try installing Arpack on its own with Pkg.add("Arpack") ? Does it produce the same error message?

**Comment by Elennahan** [comment]
It returned the entirely same error information. It may result in my installing julia in an incorrect way.

**Comment by maximerischard** [comment]
Yes, this is difficult for me to help you. Could you try downloading the regular [julia binaries](https://julialang.org/downloads/) rather than julia pro, and see if you get the same error installing Arpack?

**Comment by Elennahan** [comment]
Thanks a lot. Following your advice, I successfully installed this package.

**Comment by Elennahan** [comment]
First, thank you very much for the really handsome package! 
What I want to learn about is whether I could use this package when I would like to get treatment effect along moran than one geographical boundary, though you point its usage for 1D RDD in your paper.

**Comment by maximerischard** [comment]
Hello again, sorry for the delay. The answer depends on exactly what you mean by “more than one geographical boundary.” In the paper (which is available on arxiv), I in fact look at multiple boundaries between New York school districts. Is this the kind of application you have in mind?

**Comment by maximerischard** [comment]
@Elennahan, let me know if you need any more help.
