### ISSUE TITLE
provide instructions for preprocessing

### ISSUE THREAD

**Issue by maximerischard** [maximerischard/GeoRDD.jl#2]

**Comment by NI-RONG** [comment]
When I run the SimulatedExample.phynb,there was an error --"ArgumentError: Package GeoRDD not found in current path:- Run `import Pkg; Pkg.add("GeoRDD")` to install the GeoRDD package.", then I followed what it suggested, there was still an error "The following package names could not be resolved: * GeoRDD (not found in project, manifest or registry)". I didnt find GeoRDD either. Can you tell me how to deal with it? look forward to your answer. Thank you very much.

**Comment by maximerischard** [comment]
Thank you for your interest. The package is not registered, so it has to be installed with a direct link to github. This can be accomplished by running `import Pkg; Pkg.add("https://github.com/maximerischard/GeoRDD.jl.git")` (or `add https://github.com/maximerischard/GeoRDD.jl.git` from the [Pkg REPL](https://docs.julialang.org/en/v1/stdlib/Pkg/)).
