### ISSUE TITLE
Gaussian process object wrong type

### ISSUE THREAD

**Issue by lily-an1** [maximerischard/GeoRDD.jl#3]
Hi Maxime, I'm following your SimulatedExample.ipynb and the line:

# create the Gaussian process object from the regional data:
mgpcv = GeoRDD.MultiGPCovars(geordd, k_se+k_m, βkern, logNoise)

Gives this error: 
MethodError: Cannot `convert` an object of type GaussianProcesses.Scalar{Float64} to an object of type Float64

Just wondering if you know a workaround for this? I don't know if it's something with GeoRDD or with GaussianProcesses.

**Comment by maximerischard** [comment]
I’m sorry you encountered this error. Replacing logNoise with logNoise.value should fix that problem. I’ll have a look as soon as possible to make sure the notebook is reproducible.
